spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/muskkill?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PWD:0319}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  jwt-secret: ${JWT_SECRET:dsadsasa}
  access-exp: ${JWT_ACCESS_EXP:180000000}
  jwt-header: ${JWT_HEADER:Authorization}
  jwt-prefix: ${JWT_PREFIX:Bearer}
